# Directiva
name: Pull request notification
on: pull_request

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        
        steps:
            - name: "Hola mundo"
              run: echo "Hola mundo"

    second_jobs:
        needs:
            - first_jobs
            
        runs-on: ubuntu-latest

        steps:
            - name: Segundo trabajo
              run: echo "Ejecutar segundo hola mundo"

